# Generated by Django 5.0.3 on 2024-03-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='depatment',
            new_name='department',
        ),
    ]
