# Generated by Django 5.0.3 on 2024-03-23 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_task_members_task_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.task')),
            ],
            options={
                'verbose_name': 'task completed',
                'verbose_name_plural': 'tasks completed',
            },
        ),
    ]
