# Generated by Django 5.0.3 on 2024-03-24 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_taskcompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompleted',
            name='task',
            field=models.ForeignKey(limit_choices_to={'checklist': False}, on_delete=django.db.models.deletion.CASCADE, to='projects.task'),
        ),
    ]
