# Generated by Django 5.0.3 on 2024-03-27 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user_admin',
            field=models.ForeignKey(default=None, limit_choices_to={'is_administrator': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
